[project]
name = "softfork-simultaneous-guardian"
authors = ["Guardian Health Tech <dev@guardianhealth.io>"]
description = "A blockchain-powered wellness tracking platform ensuring data sovereignty and personal health insights"
telemetry = false
requirements = []
[contracts.guardian-wellness-tracker]
path = "contracts/guardian-wellness-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
